#!/usr/bin/env sh
printf '%s' "Cleaning:"
if [ -d "./build" ]; then
	rm -f ./build/client_gfcp_*-gridfinity 2>/dev/null || true
	rm -f ./build/server_gfcp_*-gridfinity 2>/dev/null || true
else
	printf '%s\n' " no build directory!"
	exit 1
fi
rmdir "./build" 2>/dev/null || {
	printf '%s\n' " build directory not removed!"
	exit 1
}
printf '%s\n' " clean-up completed!"

